### ISSUE TITLE
do not download files we don't intend to sketch or save

### ISSUE THREAD

**Issue by bluegenes** [sourmash-bio/sourmash_plugin_directsketch#26]
We are currently using command line flags, `--genomes-only` and `--proteomes-only` to determine whether to download genome/proteome files. However, if we're not saving FASTA files, we could/should also look at the signatures we need to build. Not building protein sigs? Don't download protein fasta!

A quick way to do this would be by checking if either `dna_sig_templates` or `prot_sig_templates` are empty, and either erroring out or adjusting the `--genomes-only` or `--proteomes-only` flags to reflect the work we need to do. Note, this needs to be done only if we're not saving FASTA files (`--keep-fastas`).

https://github.com/sourmash-bio/sourmash_plugin_directsketch/blob/main/src/directsketch.rs#L662-L663

This is likely the cause of the extra "failures" in #25, and would definitely be increasing the runtime unnecessarily!

**Comment by bluegenes** [comment]
We could also revisit the default setting -- we could just download DNA by default, for example.

**Comment by ccbaumler** [comment]
Mentioned in #25, but depending on how the script is setup. You could also tie filetype to moltype.

**Comment by bluegenes** [comment]
> You could also tie filetype to moltype. 

The only complication there is if we want to allow for translated sigs (download genome, sketch protein)
